/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-permission-manager/dbus/org.deepin.dde.Permission1.xml -a ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1Adaptor -i ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_PERMISSION1ADAPTOR_H
#define ORG_DEEPIN_DDE_PERMISSION1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Permission1
 */
class Permission1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Permission1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Permission1\">\n"
"    <method name=\"PermissionList\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"results\"/>\n"
"    </method>\n"
"    <method name=\"Request\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"permissionId\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"results\"/>\n"
"    </method>\n"
"    <method name=\"Request\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"Request\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"description\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"Set\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Reset\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"    </method>\n"
"    <method name=\"GetRegisterAppPermissionIds\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"RegistAppPermissions\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"a{ss}\" name=\"permissionsInfo\"/>\n"
"      <annotation value=\"PermissionsInfo\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"    </method>\n"
"    <method name=\"ShowDisablePermissionDialog\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"    </method>\n"
"    <method name=\"GetPermissionInfo\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"permissionInfo\"/>\n"
"    </method>\n"
"    <method name=\"SetPermissionInfo\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"GetPermissionEnable\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"SetPermissionEnable\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"permissionId\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"    </method>\n"
"    <signal name=\"PermissionInfoChanged\"/>\n"
"    <signal name=\"PermissionEnableChanged\">\n"
"      <arg type=\"s\" name=\"permissionGroup\"/>\n"
"      <arg type=\"s\" name=\"permissionId\"/>\n"
"      <arg type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    Permission1Adaptor(QObject *parent);
    virtual ~Permission1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool GetPermissionEnable(const QString &permissionGroup, const QString &permissionId);
    QString GetPermissionInfo();
    QStringList GetRegisterAppPermissionIds(const QString &appId, const QString &permissionGroup);
    QStringList PermissionList(const QString &permissionGroup);
    void RegistAppPermissions(const QString &appId, const QString &permissionGroup, PermissionsInfo permissionsInfo);
    QString Request(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &title, const QString &description);
    QString Request(const QString &appId, const QString &permissionGroup, const QString &permissionId);
    QStringList Request(const QString &appId, const QString &permissionGroup, const QStringList &permissionId);
    void Reset(const QString &appId, const QString &permissionGroup);
    void Set(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &value);
    bool SetPermissionEnable(const QString &permissionGroup, const QString &permissionId, bool enable);
    bool SetPermissionInfo(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &value);
    void ShowDisablePermissionDialog(const QString &appId, const QString &permissionGroup, const QString &permissionId);
Q_SIGNALS: // SIGNALS
    void PermissionEnableChanged(const QString &permissionGroup, const QString &permissionId, bool enable);
    void PermissionInfoChanged();
};

#endif
