/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-permission-manager/dbus/org.deepin.dde.Permission1.Client.xml -a ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.ClientAdaptor -i ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.Client.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.ClientAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ClientAdaptor
 */

ClientAdaptor::ClientAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ClientAdaptor::~ClientAdaptor()
{
    // destructor
}

QString ClientAdaptor::Request(const QString &title, const QString &description, const QString &prefer, const QStringList &options)
{
    // handle method call org.deepin.dde.Permission1.Client.Request
    QString result;
    QMetaObject::invokeMethod(parent(), "Request", Q_RETURN_ARG(QString, result), Q_ARG(QString, title), Q_ARG(QString, description), Q_ARG(QString, prefer), Q_ARG(QStringList, options));
    return result;
}

QString ClientAdaptor::ShowDisablePermissionDialog(const QString &title, const QString &description, const QStringList &options)
{
    // handle method call org.deepin.dde.Permission1.Client.ShowDisablePermissionDialog
    QString result;
    QMetaObject::invokeMethod(parent(), "ShowDisablePermissionDialog", Q_RETURN_ARG(QString, result), Q_ARG(QString, title), Q_ARG(QString, description), Q_ARG(QStringList, options));
    return result;
}

