/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-permission-manager/dbus/org.deepin.dde.Permission1.xml -a ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1Adaptor -i ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Permission1Adaptor
 */

Permission1Adaptor::Permission1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Permission1Adaptor::~Permission1Adaptor()
{
    // destructor
}

bool Permission1Adaptor::GetPermissionEnable(const QString &permissionGroup, const QString &permissionId)
{
    // handle method call org.deepin.dde.Permission1.GetPermissionEnable
    bool enable;
    QMetaObject::invokeMethod(parent(), "GetPermissionEnable", Q_RETURN_ARG(bool, enable), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId));
    return enable;
}

QString Permission1Adaptor::GetPermissionInfo()
{
    // handle method call org.deepin.dde.Permission1.GetPermissionInfo
    QString permissionInfo;
    QMetaObject::invokeMethod(parent(), "GetPermissionInfo", Q_RETURN_ARG(QString, permissionInfo));
    return permissionInfo;
}

QStringList Permission1Adaptor::GetRegisterAppPermissionIds(const QString &appId, const QString &permissionGroup)
{
    // handle method call org.deepin.dde.Permission1.GetRegisterAppPermissionIds
    QStringList result;
    QMetaObject::invokeMethod(parent(), "GetRegisterAppPermissionIds", Q_RETURN_ARG(QStringList, result), Q_ARG(QString, appId), Q_ARG(QString, permissionGroup));
    return result;
}

QStringList Permission1Adaptor::PermissionList(const QString &permissionGroup)
{
    // handle method call org.deepin.dde.Permission1.PermissionList
    QStringList results;
    QMetaObject::invokeMethod(parent(), "PermissionList", Q_RETURN_ARG(QStringList, results), Q_ARG(QString, permissionGroup));
    return results;
}

void Permission1Adaptor::RegistAppPermissions(const QString &appId, const QString &permissionGroup, PermissionsInfo permissionsInfo)
{
    // handle method call org.deepin.dde.Permission1.RegistAppPermissions
    QMetaObject::invokeMethod(parent(), "RegistAppPermissions", Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(PermissionsInfo, permissionsInfo));
}

QString Permission1Adaptor::Request(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &title, const QString &description)
{
    // handle method call org.deepin.dde.Permission1.Request
    QString result;
    QMetaObject::invokeMethod(parent(), "Request", Q_RETURN_ARG(QString, result), Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId), Q_ARG(QString, title), Q_ARG(QString, description));
    return result;
}

QString Permission1Adaptor::Request(const QString &appId, const QString &permissionGroup, const QString &permissionId)
{
    // handle method call org.deepin.dde.Permission1.Request
    QString result;
    QMetaObject::invokeMethod(parent(), "Request", Q_RETURN_ARG(QString, result), Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId));
    return result;
}

QStringList Permission1Adaptor::Request(const QString &appId, const QString &permissionGroup, const QStringList &permissionId)
{
    // handle method call org.deepin.dde.Permission1.Request
    QStringList results;
    QMetaObject::invokeMethod(parent(), "Request", Q_RETURN_ARG(QStringList, results), Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QStringList, permissionId));
    return results;
}

void Permission1Adaptor::Reset(const QString &appId, const QString &permissionGroup)
{
    // handle method call org.deepin.dde.Permission1.Reset
    QMetaObject::invokeMethod(parent(), "Reset", Q_ARG(QString, appId), Q_ARG(QString, permissionGroup));
}

void Permission1Adaptor::Set(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &value)
{
    // handle method call org.deepin.dde.Permission1.Set
    QMetaObject::invokeMethod(parent(), "Set", Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId), Q_ARG(QString, value));
}

bool Permission1Adaptor::SetPermissionEnable(const QString &permissionGroup, const QString &permissionId, bool enable)
{
    // handle method call org.deepin.dde.Permission1.SetPermissionEnable
    bool result;
    QMetaObject::invokeMethod(parent(), "SetPermissionEnable", Q_RETURN_ARG(bool, result), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId), Q_ARG(bool, enable));
    return result;
}

bool Permission1Adaptor::SetPermissionInfo(const QString &appId, const QString &permissionGroup, const QString &permissionId, const QString &value)
{
    // handle method call org.deepin.dde.Permission1.SetPermissionInfo
    bool result;
    QMetaObject::invokeMethod(parent(), "SetPermissionInfo", Q_RETURN_ARG(bool, result), Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId), Q_ARG(QString, value));
    return result;
}

void Permission1Adaptor::ShowDisablePermissionDialog(const QString &appId, const QString &permissionGroup, const QString &permissionId)
{
    // handle method call org.deepin.dde.Permission1.ShowDisablePermissionDialog
    QMetaObject::invokeMethod(parent(), "ShowDisablePermissionDialog", Q_ARG(QString, appId), Q_ARG(QString, permissionGroup), Q_ARG(QString, permissionId));
}

