/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-permission-manager/dbus/org.deepin.dde.Permission1.Client.xml -a ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.ClientAdaptor -i ./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.Client.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_PERMISSION1_CLIENTADAPTOR_H
#define ORG_DEEPIN_DDE_PERMISSION1_CLIENTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-permission-manager/toolGenerate/qdbusxml2cpp/org.deepin.dde.Permission1.Client.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Permission1.Client
 */
class ClientAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Permission1.Client")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Permission1.Client\">\n"
"    <method name=\"Request\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"description\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"prefer\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"options\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"ShowDisablePermissionDialog\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"description\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"options\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ClientAdaptor(QObject *parent);
    virtual ~ClientAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString Request(const QString &title, const QString &description, const QString &prefer, const QStringList &options);
    QString ShowDisablePermissionDialog(const QString &title, const QString &description, const QStringList &options);
Q_SIGNALS: // SIGNALS
};

#endif
